# Generated by Django 2.2.3 on 2019-11-26 07:57

import adminhome.models
import adminhome.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('joining_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=500)),
                ('joining_date', models.DateField()),
                ('is_teacher', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('resume', models.FileField(upload_to=adminhome.models.get_upload_path, validators=[adminhome.validators.validate_file_extension])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.CharField(max_length=20)),
                ('is_registered', models.BooleanField(default=False)),
                ('has_principal', models.BooleanField(default=False)),
                ('school_name', models.CharField(max_length=200)),
                ('class_upto', models.PositiveIntegerField(null=True)),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment_no', models.CharField(max_length=20)),
                ('roll_no', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=500)),
                ('admission_date', models.DateField()),
                ('study', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=500)),
                ('joining_date', models.DateField()),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('class_teacher_of', models.IntegerField(null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('resume', models.FileField(upload_to=adminhome.models.get_upload_path, validators=[adminhome.validators.validate_file_extension])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.School')),
            ],
        ),
    ]
