# Generated by Django 2.2.3 on 2019-08-05 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0002_parent_principal_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localadmin',
            name='name',
        ),
        migrations.AddField(
            model_name='localadmin',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='localadmin',
            name='joining_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='localadmin',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
