# Generated by Django 2.2.3 on 2019-08-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0003_auto_20190805_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localadmin',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='localadmin',
            name='joining_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='localadmin',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='principal',
            name='joining_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='joining_date',
            field=models.DateField(),
        ),
    ]
