# Generated by Django 2.2.3 on 2019-08-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=500)),
                ('school_address_line_1', models.CharField(max_length=1000)),
                ('line_2', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('principal_name', models.CharField(max_length=100)),
                ('principal_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Parents',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='principal',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='principal',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='principal',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
