# Generated by Django 2.2.3 on 2019-08-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0002_auto_20190801_2018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Principal',
            new_name='Principle',
        ),
        migrations.RenameField(
            model_name='principle',
            old_name='username',
            new_name='name',
        ),
    ]
