# Generated by Django 2.2.3 on 2019-08-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0003_auto_20190804_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Principle',
        ),
    ]
