# Generated by Django 2.2.3 on 2019-08-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0004_auto_20190805_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('confirm_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Principal',
        ),
        migrations.RemoveField(
            model_name='school',
            name='email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='principal_email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='principal_name',
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='line_2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_address_line_1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
