# Generated by Django 2.2.3 on 2019-09-06 17:50

import adminhome.validators
from django.db import migrations, models
import django.db.models.deletion
import teacherhome.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20)),
                ('study', models.PositiveIntegerField()),
                ('absent_on', models.DateField()),
                ('name', models.CharField(max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.School')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('subject', models.CharField(max_length=30)),
                ('assign_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('assignment_file', models.FileField(upload_to=teacherhome.models.get_upload_path, validators=[adminhome.validators.validate_file_extension])),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminhome.Teacher')),
            ],
        ),
    ]
