# Generated by Django 2.2.3 on 2019-08-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
                ('assign_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('assignement_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('is_present', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SendAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=1000)),
                ('email_id', models.CharField(max_length=50)),
                ('attendance_message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=1000)),
                ('email_id', models.CharField(max_length=50)),
                ('report_message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SendResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=1000)),
                ('email_id', models.CharField(max_length=50)),
                ('result', models.FileField(upload_to='')),
            ],
        ),
    ]
