# Generated by Django 2.2.3 on 2019-11-26 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('announcement_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('audience', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('announcer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.Principal')),
            ],
        ),
    ]
